apiVersion: v1
kind: Namespace
metadata:
  name: angular


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misanuncios-ui
  namespace: angular
  labels:
    app: misanuncios-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: misanuncios-ui
  template:
    metadata:
      labels:
        app: misanuncios-ui
    spec:
      containers:
        - name: misanuncios-ui
          image: yaagoub/misanuncios-ui:latest
          ports:
            - containerPort: 4200


---

apiVersion: v1
kind: Service
metadata:
  namespace: angular
  name: misanuncios-ui
spec:
  type: LoadBalancer
  ports:
    - port: 4201
      targetPort: 4200
  selector:
    app: misanuncios-ui

    
