version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: misanuncios  # Cambié el nombre de la base de datos a 'misanuncios'
      MYSQL_ROOT_PASSWORD: yaagoub
      MYSQL_USER: yaagoub
      MYSQL_PASSWORD: yaagoub
    ports:
      - "3307:3306"  # Cambia 3306 a 3307 o cualquier otro puerto disponible en tu máquina
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springboot-mysql-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/misanuncios?allowPublicKeyRetrieval=true&useSSL=true  # Cambié la base de datos a 'misanuncios'
      SPRING_DATASOURCE_USERNAME: yaagoub
      SPRING_DATASOURCE_PASSWORD: yaagoub
    depends_on:
      - mysql
    networks:
      - springboot-mysql-network

networks:
  springboot-mysql-network:

volumes:
  mysql_data:
